// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OnConnectedArgs {}

impl From<OnConnectedArgs> for super::Reducer {
    fn from(args: OnConnectedArgs) -> Self {
        Self::OnConnected
    }
}

impl __sdk::InModule for OnConnectedArgs {
    type Module = super::RemoteModule;
}

pub struct OnConnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `on_connected`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait on_connected {
    /// Request that the remote module invoke the reducer `on_connected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_on_connected`] callbacks.
    fn on_connected(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `on_connected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OnConnectedCallbackId`] can be passed to [`Self::remove_on_on_connected`]
    /// to cancel the callback.
    fn on_on_connected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnConnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_on_connected`],
    /// causing it not to run in the future.
    fn remove_on_on_connected(&self, callback: OnConnectedCallbackId);
}

impl on_connected for super::RemoteReducers {
    fn on_connected(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("on_connected", OnConnectedArgs {})
    }
    fn on_on_connected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnConnectedCallbackId {
        OnConnectedCallbackId(self.imp.on_reducer(
            "on_connected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OnConnected {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_on_connected(&self, callback: OnConnectedCallbackId) {
        self.imp.remove_on_reducer("on_connected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `on_connected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_on_connected {
    /// Set the call-reducer flags for the reducer `on_connected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn on_connected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_on_connected for super::SetReducerFlags {
    fn on_connected(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("on_connected", flags);
    }
}
