// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_position_type::PlayerPosition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_positions`.
///
/// Obtain a handle from the [`PlayerPositionsTableAccess::player_positions`] method on [`super::RemoteTables`],
/// like `ctx.db.player_positions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_positions().on_insert(...)`.
pub struct PlayerPositionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerPosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_positions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerPositionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerPositionsTableHandle`], which mediates access to the table `player_positions`.
    fn player_positions(&self) -> PlayerPositionsTableHandle<'_>;
}

impl PlayerPositionsTableAccess for super::RemoteTables {
    fn player_positions(&self) -> PlayerPositionsTableHandle<'_> {
        PlayerPositionsTableHandle {
            imp: self.imp.get_table::<PlayerPosition>("player_positions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerPositionsInsertCallbackId(__sdk::CallbackId);
pub struct PlayerPositionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerPositionsTableHandle<'ctx> {
    type Row = PlayerPosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerPosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerPositionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerPositionsInsertCallbackId {
        PlayerPositionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerPositionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerPositionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerPositionsDeleteCallbackId {
        PlayerPositionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerPositionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerPosition>("player_positions");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct PlayerPositionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerPositionsTableHandle<'ctx> {
    type UpdateCallbackId = PlayerPositionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerPositionsUpdateCallbackId {
        PlayerPositionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerPositionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerPosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerPosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `player_positions`,
/// which allows point queries on the field of the same name
/// via the [`PlayerPositionsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_positions().id().find(...)`.
pub struct PlayerPositionsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerPosition, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerPositionsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `player_positions`.
    pub fn id(&self) -> PlayerPositionsIdUnique<'ctx> {
        PlayerPositionsIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerPositionsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerPosition> {
        self.imp.find(col_val)
    }
}
