// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_window_type::PlayerWindow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players_windows`.
///
/// Obtain a handle from the [`PlayersWindowsTableAccess::players_windows`] method on [`super::RemoteTables`],
/// like `ctx.db.players_windows()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_windows().on_insert(...)`.
pub struct PlayersWindowsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerWindow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players_windows`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersWindowsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersWindowsTableHandle`], which mediates access to the table `players_windows`.
    fn players_windows(&self) -> PlayersWindowsTableHandle<'_>;
}

impl PlayersWindowsTableAccess for super::RemoteTables {
    fn players_windows(&self) -> PlayersWindowsTableHandle<'_> {
        PlayersWindowsTableHandle {
            imp: self.imp.get_table::<PlayerWindow>("players_windows"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersWindowsInsertCallbackId(__sdk::CallbackId);
pub struct PlayersWindowsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersWindowsTableHandle<'ctx> {
    type Row = PlayerWindow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerWindow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersWindowsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersWindowsInsertCallbackId {
        PlayersWindowsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersWindowsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersWindowsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersWindowsDeleteCallbackId {
        PlayersWindowsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersWindowsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerWindow>("players_windows");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct PlayersWindowsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayersWindowsTableHandle<'ctx> {
    type UpdateCallbackId = PlayersWindowsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayersWindowsUpdateCallbackId {
        PlayersWindowsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayersWindowsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerWindow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerWindow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `players_windows`,
/// which allows point queries on the field of the same name
/// via the [`PlayersWindowsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_windows().id().find(...)`.
pub struct PlayersWindowsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerWindow, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayersWindowsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `players_windows`.
    pub fn id(&self) -> PlayersWindowsIdUnique<'ctx> {
        PlayersWindowsIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayersWindowsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerWindow> {
        self.imp.find(col_val)
    }
}
