// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_position_type::PlayerPosition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players_positions`.
///
/// Obtain a handle from the [`PlayersPositionsTableAccess::players_positions`] method on [`super::RemoteTables`],
/// like `ctx.db.players_positions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_positions().on_insert(...)`.
pub struct PlayersPositionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerPosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players_positions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersPositionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersPositionsTableHandle`], which mediates access to the table `players_positions`.
    fn players_positions(&self) -> PlayersPositionsTableHandle<'_>;
}

impl PlayersPositionsTableAccess for super::RemoteTables {
    fn players_positions(&self) -> PlayersPositionsTableHandle<'_> {
        PlayersPositionsTableHandle {
            imp: self.imp.get_table::<PlayerPosition>("players_positions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersPositionsInsertCallbackId(__sdk::CallbackId);
pub struct PlayersPositionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersPositionsTableHandle<'ctx> {
    type Row = PlayerPosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerPosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersPositionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersPositionsInsertCallbackId {
        PlayersPositionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersPositionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersPositionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersPositionsDeleteCallbackId {
        PlayersPositionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersPositionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerPosition>("players_positions");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct PlayersPositionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayersPositionsTableHandle<'ctx> {
    type UpdateCallbackId = PlayersPositionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayersPositionsUpdateCallbackId {
        PlayersPositionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayersPositionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerPosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerPosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `players_positions`,
/// which allows point queries on the field of the same name
/// via the [`PlayersPositionsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_positions().id().find(...)`.
pub struct PlayersPositionsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerPosition, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayersPositionsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `players_positions`.
    pub fn id(&self) -> PlayersPositionsIdUnique<'ctx> {
        PlayersPositionsIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayersPositionsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerPosition> {
        self.imp.find(col_val)
    }
}
