// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerWindow {
    pub id: __sdk::Identity,
    pub lr_br_x: f32,
    pub lr_br_y: f32,
    pub lr_tl_x: f32,
    pub lr_tl_y: f32,
    pub lr_size: f32,
    pub hr_br_x: f32,
    pub hr_br_y: f32,
    pub hr_tl_x: f32,
    pub hr_tl_y: f32,
    pub hr_size: f32,
    pub recompute_distance: f32,
}

impl __sdk::InModule for PlayerWindow {
    type Module = super::RemoteModule;
}
