// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_window_update_type::PlayerWindowUpdate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players_window_updates`.
///
/// Obtain a handle from the [`PlayersWindowUpdatesTableAccess::players_window_updates`] method on [`super::RemoteTables`],
/// like `ctx.db.players_window_updates()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_window_updates().on_insert(...)`.
pub struct PlayersWindowUpdatesTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerWindowUpdate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players_window_updates`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersWindowUpdatesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersWindowUpdatesTableHandle`], which mediates access to the table `players_window_updates`.
    fn players_window_updates(&self) -> PlayersWindowUpdatesTableHandle<'_>;
}

impl PlayersWindowUpdatesTableAccess for super::RemoteTables {
    fn players_window_updates(&self) -> PlayersWindowUpdatesTableHandle<'_> {
        PlayersWindowUpdatesTableHandle {
            imp: self
                .imp
                .get_table::<PlayerWindowUpdate>("players_window_updates"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersWindowUpdatesInsertCallbackId(__sdk::CallbackId);
pub struct PlayersWindowUpdatesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersWindowUpdatesTableHandle<'ctx> {
    type Row = PlayerWindowUpdate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerWindowUpdate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersWindowUpdatesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersWindowUpdatesInsertCallbackId {
        PlayersWindowUpdatesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersWindowUpdatesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersWindowUpdatesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersWindowUpdatesDeleteCallbackId {
        PlayersWindowUpdatesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersWindowUpdatesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerWindowUpdate>("players_window_updates");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PlayersWindowUpdatesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayersWindowUpdatesTableHandle<'ctx> {
    type UpdateCallbackId = PlayersWindowUpdatesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayersWindowUpdatesUpdateCallbackId {
        PlayersWindowUpdatesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayersWindowUpdatesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerWindowUpdate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerWindowUpdate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `players_window_updates`,
/// which allows point queries on the field of the same name
/// via the [`PlayersWindowUpdatesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_window_updates().id().find(...)`.
pub struct PlayersWindowUpdatesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerWindowUpdate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayersWindowUpdatesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `players_window_updates`.
    pub fn id(&self) -> PlayersWindowUpdatesIdUnique<'ctx> {
        PlayersWindowUpdatesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayersWindowUpdatesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerWindowUpdate> {
        self.imp.find(col_val)
    }
}
