// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_position_type::PlayerPosition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players_positions_lr`.
///
/// Obtain a handle from the [`PlayersPositionsLrTableAccess::players_positions_lr`] method on [`super::RemoteTables`],
/// like `ctx.db.players_positions_lr()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_positions_lr().on_insert(...)`.
pub struct PlayersPositionsLrTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerPosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players_positions_lr`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersPositionsLrTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersPositionsLrTableHandle`], which mediates access to the table `players_positions_lr`.
    fn players_positions_lr(&self) -> PlayersPositionsLrTableHandle<'_>;
}

impl PlayersPositionsLrTableAccess for super::RemoteTables {
    fn players_positions_lr(&self) -> PlayersPositionsLrTableHandle<'_> {
        PlayersPositionsLrTableHandle {
            imp: self.imp.get_table::<PlayerPosition>("players_positions_lr"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersPositionsLrInsertCallbackId(__sdk::CallbackId);
pub struct PlayersPositionsLrDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersPositionsLrTableHandle<'ctx> {
    type Row = PlayerPosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerPosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersPositionsLrInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersPositionsLrInsertCallbackId {
        PlayersPositionsLrInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersPositionsLrInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersPositionsLrDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersPositionsLrDeleteCallbackId {
        PlayersPositionsLrDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersPositionsLrDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerPosition>("players_positions_lr");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct PlayersPositionsLrUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayersPositionsLrTableHandle<'ctx> {
    type UpdateCallbackId = PlayersPositionsLrUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayersPositionsLrUpdateCallbackId {
        PlayersPositionsLrUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayersPositionsLrUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerPosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerPosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `players_positions_lr`,
/// which allows point queries on the field of the same name
/// via the [`PlayersPositionsLrIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players_positions_lr().id().find(...)`.
pub struct PlayersPositionsLrIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerPosition, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayersPositionsLrTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `players_positions_lr`.
    pub fn id(&self) -> PlayersPositionsLrIdUnique<'ctx> {
        PlayersPositionsLrIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayersPositionsLrIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerPosition> {
        self.imp.find(col_val)
    }
}
