[package]
name = "bots"
version = "0.1.0"
edition = "2024"

[dependencies]
bindings = { path = "../bindings" }
spacetimedb-sdk = "1.1.1"
rand = "0.9.1"
tokio = "1.45.1"
clap = { version = "4.5.39", features = ["derive"] }
