// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `players`.
///
/// Obtain a handle from the [`PlayersTableAccess::players`] method on [`super::RemoteTables`],
/// like `ctx.db.players()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.players().on_insert(...)`.
pub struct PlayersTableHandle<'ctx> {
    imp: __sdk::TableHandle<Player>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `players`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayersTableHandle`], which mediates access to the table `players`.
    fn players(&self) -> PlayersTableHandle<'_>;
}

impl PlayersTableAccess for super::RemoteTables {
    fn players(&self) -> PlayersTableHandle<'_> {
        PlayersTableHandle {
            imp: self.imp.get_table::<Player>("players"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayersInsertCallbackId(__sdk::CallbackId);
pub struct PlayersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayersTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersInsertCallbackId {
        PlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayersDeleteCallbackId {
        PlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Player>("players");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Player>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Player>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
